# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CollectionViewSwipeToDelete' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxDataSources'
    pod 'SwipeToDeleteCollectionView'
  # Pods for CollectionViewSwipeToDelete

end
